name: E2E
author: EnricoMi
description: Github Action to run end-to-end tests against a Spark and Scala version

inputs:
  spark_version:
    description: Spark version to build against, e.g. "3.5.5" or "4.1.0-SNAPSHOT"
    required: true
  scala_version:
    description: Scala version to build with, e.g. "2.13.8"
    required: true
  java_version:
    description: Java version to build with, e.g. "11"
    required: true

runs:
  using: composite
  steps:
  - name: Checkout
    uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    with:
      path: armada-spark

  - name: Restore Maven packages cache
    uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
    with:
      path: ~/.m2/repository
      key: ${{ runner.os }}-mvn-e2e-${{ inputs.spark_version }}-${{ inputs.scala_version }}-${{ hashFiles('armada-spark/pom.xml') }}
      restore-keys:
        ${{ runner.os }}-mvn-e2e-${{ inputs.spark_version }}-${{ inputs.scala_version }}-${{ hashFiles('armada-spark/pom.xml') }}
        ${{ runner.os }}-mvn-e2e-${{ inputs.spark_version }}-${{ inputs.scala_version }}-
  - name: Move docker
    run: |
      # Moving docker to save space
      echo "::group::moving Docker"
      df -h /mnt
      sudo systemctl stop docker
      sudo cp -rpd /var/lib/docker /mnt
      sudo mv /var/lib/docker /var/lib/docker.old
      sudo ln -s /mnt/docker /var/lib
      sudo systemctl start docker
      df -h /mnt
      echo "::endgroup::"
    shell: bash
  - name: Setup JDK
    uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
    with:
      java-version: ${{ inputs.java_version }}
      distribution: 'zulu'
  - name: Setup Go
    id: setup-go
    uses: armadaproject/armada-operator/.github/actions/setup-go-cache@72ecbbdfddd147af7be300cbea7f0d870004e56c # main
    with:
      cache-prefix: go-e2e

  - name: Set Spark and Scala versions
    working-directory: armada-spark
    run: |
      SPARK_VER="${{ inputs.spark_version }}"
      SCALA_VER="${{ inputs.scala_version }}"
      
      # Compute the short binary versions (ex: 4.1.1 -> 4.1)
      SPARK_BIN=$(echo "$SPARK_VER" | cut -d. -f1-2)
      SCALA_BIN=$(echo "$SCALA_VER" | cut -d. -f1-2)
      
      # Export everything to the global GitHub Actions environment
      echo "MAVEN_PROFILES=spark${SPARK_VER},scala${SCALA_VER}" >> $GITHUB_ENV
      echo "SPARK_VERSION=${SPARK_VER}" >> $GITHUB_ENV
      echo "SPARK_BIN_VERSION=${SPARK_BIN}" >> $GITHUB_ENV
      echo "SCALA_VERSION=${SCALA_VER}" >> $GITHUB_ENV
      echo "SCALA_BIN_VERSION=${SCALA_BIN}" >> $GITHUB_ENV
    shell: bash
  - name: Fetch mvn dependencies
    continue-on-error: true
    working-directory: armada-spark
    run: |
      # Fetch mvn dependencies
      echo "::group::mvn go-offline"
      mvn --batch-mode --update-snapshots dependency:go-offline -P$MAVEN_PROFILES
      echo "::endgroup::"
    shell: bash
  - name: Build test jars
    working-directory: armada-spark
    run: |
      # Build test jars
      echo "::group::mvn test-compile"
      mvn --batch-mode test-compile -P$MAVEN_PROFILES
      echo "::endgroup::"
    shell: bash
  - name: Build package
    working-directory: armada-spark
    run: |
      # Build package
      echo "::group::mvn package"
      mvn --batch-mode package -P$MAVEN_PROFILES
      echo "::endgroup::"
    shell: bash
  - name: Build image
    env:
      JAVA_VERSION: ${{ inputs.java_version }}
    run: |
      # Build image
      echo "::group::createImage.sh"
      ./armada-spark/scripts/createImage.sh -p -e
      echo "::endgroup::"
    shell: bash
  - name: Test job processing
    id: submit
    run: |
      echo "::group::dev-e2e.sh"
      ./armada-spark/scripts/dev-e2e.sh -q test
      echo "::endgroup::"
    shell: bash
